### ISSUE TITLE
Understanding protocols

### ISSUE THREAD

**Issue by genderev** [r-efi/r-efi#29]
1. Once you have acquired the handle for a device path, how do you find the hardware ID correlated to the given device path? I read that this would require the PCI I/O Protocol but I haven't seen this protocol in any crates and am not sure how to implement it.
2. How would one implement a protocol documented in this crate? I tried:

```
use crate::proto::Protocol; // the crate is bootloader
use crate::unsafe_guid;
use r_efi::protocols::simple_network::Protocol as SimpleNetwork;

#[unsafe_guid("a19832b9-ac25-11d3-9a2d-0090273fc14d")]
#[derive(Protocol)]
struct SimpleNetwork;

```

but I'm not sure this will work.

**Comment by dvdhrm** [comment]
>     1. Once you have acquired the handle for a device path, how do you find the hardware ID correlated to the given device path? I read that this would require the PCI I/O Protocol but I haven't seen this protocol in any crates and am not sure how to implement it.

What exactly do you mean with `Hardware ID`? PCI and USB devices have vendorID/deviceID/subsystem/revision, but I am not sure what you refer to with `Hardware ID`.

>     2. How would one implement a protocol documented in this crate? I tried:
> 
> 
> ```
> use crate::proto::Protocol; // the crate is bootloader
> use crate::unsafe_guid;
> use r_efi::protocols::simple_network::Protocol as SimpleNetwork;
> 
> #[unsafe_guid("a19832b9-ac25-11d3-9a2d-0090273fc14d")]
> #[derive(Protocol)]
> struct SimpleNetwork;
> ```

The `r-efi` crate is a mere transpose of the UEFI constants and definitions from the official UEFI specification into rust code. It does not provide any utility functions or implementation aids. The UEFI specification is the ultimate reference to learn how to implement UEFI protocols, or write UEFI applications. The `r-efi` crate will provide you all code that is mentioned in the specification, but in Rust rather than C.

Crates like `uefi-rs` (which you use in this example via `proto::Protocol` and `unsafe_guid`) provide convenient helpers and infrastructure to simplify writing UEFI applications. The `r-efi` crate can be used to supplement those convenience-crates when they lack support for specific UEFI features.

To answer your question: To implement a UEFI protocol, you have to implement all the callback-functions defined in the respective `Protocol` structure. Then you create an instance of said structure, point all the members to the right functions and then register your protocol via the UEFI driver model.

**Comment by genderev** [comment]
> What exactly do you mean with Hardware ID? 

The combination of vendor ID and device ID is the hardware ID. In other words: how do you actually use a device path handle? 

> To implement a UEFI protocol, you have to implement all the callback-functions defined in the respective Protocol structure. Then you create an instance of said structure, point all the members to the right functions and then register your protocol via the UEFI driver model.

I only want to implement the Simple Network Protocol to discover information about the network interface controller. This seems unnecessary but I'm not sure how else to find the device path of the network interface controller or other information about the NIC.

Could you enumerate PCI to find the network interface controller? How?

**Comment by dvdhrm** [comment]
> I only want to implement the Simple Network Protocol to discover information about the network interface controller. This seems unnecessary but I'm not sure how else to find the device path of the network interface controller or other information about the NIC.
> 
> Could you enumerate PCI to find the network interface controller? How?

I think you are confusing "implementing a protocol" with "using a protocol". The UEFI firmware implements the Simple Network Protocol for you, you would only use it. Maybe I am misunderstanding you, but I think you don't actually want to implement the protocol (which still would be possible, don't get me wrong).

The `LocateHandleBuffer` function on UEFI BootServices allows to find UEFI handles that implement a specific protocol. You can use it to find all handles that implement the Simple Network Protocol. For instance, see this example:

https://stackoverflow.com/questions/50914308/how-to-wait-for-network-packet-with-gnu-efi-simple-networking

The UEFI specification section 7.3 "Protocol Handler Services" describes the UEFI driver model and how to find specific devices and handles.

Note that the `r-efi` project does not define a new way to interface with UEFI. Instead, it follows exactly how the UEFI specification defines UEFI programming. Hence, any examples you find for UEFI programming should be easy to translate into `r-efi`. The tianocore/edk2 repository contains a lot of information on how UEFI works, and lots of code-examples that show how to use the UEFI driver model.

Lastly, note that `r-efi` does not have all UEFI protocols transposed (not even close). This is an ongoing process, and mostly done on-demand. So if there is a request for more UEFI protocols, we will import them following the exact naming scheme of the specification, but converted to Rust.

**Comment by genderev** [comment]
Ahh, I see. Thanks.
