### ISSUE TITLE
Reevaluating const and mut pointers in Spec

### ISSUE THREAD

**Issue by Ayush1325** [r-efi/r-efi#46]
According to the [edk2 C Coding Standard Specification](https://tianocore-docs.github.io/edk2-CCodingStandardsSpecification/draft/5_source_files/56_declarations_and_types.html#table-8-efi-constants), there are 3 types of `CONST` declaration in UEFI Spec:

1. Pointer to Constant:
```c
CONST UINTN * PointerToConst;
```
PointerToConst is a variable pointer to a constant UINTN.

2. Constant pointer to variable:
```c
UINTN * CONST ConstPointer;
```
ConstPointer is a constant pointer to a variable UINTN.

3. Constant pointer to constant:
```c    
CONST UINTN * CONST ConstPointerToConst;
```
ConstPointerToConst is a constant pointer to a constant UINTN.

I think r-efi currently uses `const` pointers in the declarations of type-1 in some cases, and this might not be correct.

**Comment by dvdhrm** [comment]
The two raw pointer types `*const` and `*mut` can be cast via `as` without any UB concerns. It is completely safe to take a `*const` pointer, cast it to `*mut` and then use it to write to it. However, the caller must make sure not to violate any safety guarantees of the variable this points to. So any UB concerns always stem from the safety guarantees of the surrounding code, not of the raw-pointer handling.

The major difference between them is that immutable references cannot coerce into `*mut` pointers, but only `*const` pointers. So if you have a immutable reference `&var`, it is automatically cast to `*const var` if required. A cast to `*mut var` has to be explicit and go via an intermediate `*const var`.
This can be both good and bad: While allowing the automatic coercion can be easy to use, it can also trick API users to think it is safe. So my conclusion here is to only ever use `*const` in our APIs *IFF* it is really safe to have an immutable reference as input / output.

Now there is a major difference between `const` in C / UEFI, and immutable references in Rust. In Rust they require you to guarantee the value does not change underneath you, as long as you hold the reference. I C, however, it can often just mean the value is not modified *through that pointer*. But it still can be modified via a mutable pointer that exists at the same time (not talking about multi-threaded execution here, but more about pointer lifetime in the same thread of execution).

Lastly, C allows to easily violate the `const` annotation and just cast it to whatever you like. This is not necessarily UB, and thus happens in the wild. Lots of APIs pass mutable pointers through intermediate `const` pointers. While it should be easy to detect this in most cases, it is sometimes not really obvious.

My general conclusion to this is to default to `*mut`. Always. But in select cases allow for `*const`. In particular, UEFI **input** values can be marked `*const` more easily, but output pointers really, really shouldn't. It would incorrectly allow easy coercion to immutable references, which would be wrong as described above.

Since all this can be quite tricky, we did, so far, resort to `*mut` everywhere with the exception of strings (and some oversights in the HII code). I am open to extend this to other situations, but I haven't really felt much need for it so far, given that an easy `as`-cast woks around this, anyway. It would, however, improve the self-documentation of the API quite a bit. Sadly, there is no real Rust equivalent to the `const` annotation in C, so we cannot blindly take those over.

Note that I might be wrong on some of these points. I tried to track all this down, but official Rust documentation on unsafe operations are pretty scarce and even happen to be misleading or wrong. So, please correct me if I got something wrong here.

**Comment by Ayush1325** [comment]
No, I think you are correct for the most part. 

I am specifically referring to the use of `*const` in the UEFI input values. In some of the APIs which currently use `*const` like [`protocols::device_path_from_text`](https://github.com/r-efi/r-efi/blob/cfa10bdfe46f2f283d2a93f179c6feb699c4b58a/src/protocols/device_path_from_text.rs#L15), the spec marks them `CONST` of type-1 (I think), which seems to be different from `*const` (which seems more like type-2 and type-3).

**Comment by dvdhrm** [comment]
This is now documented in `lib.rs`. I think we should default to `*mut`. Whenever we want to use `*const`, we should strongly re-evaluate why this is necessary and safe.

Thanks for pointing this out!
