### ISSUE TITLE
Consider adding `Ord` for base::Guid?

### ISSUE THREAD

**Issue by joschock** [r-efi/r-efi#80]
I've ended up newtyping Guid a number of places to add `Ord` e.g. so that I can use Guid as a key in a map. Would there be any objections to something like the following for Guid? If this makes sense, I'm happy to make a PR with it.

```
impl PartialOrd for Guid {
  fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
    Some(self.cmp(other))
  }
}
impl Ord for Guid {
  fn cmp(&self, other: &Self) -> Ordering {
    self.as_bytes().cmp(other.as_bytes())
  }
}

**Comment by dvdhrm** [comment]
Any particular reason to open-code it instead of using `derive`? The standard library does this as well, but I couldn't see an explanation. Is this to improve performance? Or is this a safety net to ensure Ord and PartialOrd are compatible?

Anyway, I filed a PR to derive and impl several traits for the basic types. Feel free to have a look and thanks for the reminder that we missed those!

**Comment by joschock** [comment]
Thanks! Changes look good. The open-code was just because I cut-and-pasted it from the newtype implementation I was using without thinking much. No objecting to `derive` approach instead.

**Comment by dvdhrm** [comment]
Excellent! Applied and merged. I will push out a minor release later!
