### ISSUE TITLE
New release of r-efi

### ISSUE THREAD

**Issue by Ayush1325** [r-efi/r-efi#81]
I would like to have a new release of r-efi with #79 for inclusion in Rust std https://github.com/rust-lang/rust/pull/123196#discussion_r1597674735

**Comment by dvdhrm** [comment]
Generally, I don't mind publishing a release, but I just want to clarify that #79 is **not** enough to make the variadic calls usable. If it wasn't for backwards compatibility, I would drop these functions and replace them by a `usize`.

If you want to use them from `std`, and if you *can* use unstable features, then I recommend defining your own function type and transmuting the fn-pointer. But we cannot do that in `r-efi`, since we explicitly support the stable channel.

**Comment by dvdhrm** [comment]
(Published to crates.io)
